# Generated by Django 3.2.4 on 2021-06-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210624_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mod',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تعديل'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر'),
        ),
    ]
