# Generated by Django 3.2.4 on 2021-06-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210624_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='صورة'),
        ),
    ]
